version: '3.9'
services:
  web:
    build: ./web
    container_name: web
    volumes:
      - ./web:/web
    ports:
      - '5000:80'
  api:
    build: .
    container_name: api
    ports:
      - '5001:5000'
    volumes:
      - ./sketch_api:/sketch_api
    environment:
      FLASK_ENV: development
