version: '3.9'
services:
  web:
    build: ./web
    container_name: web
    ports:
      - '5000:80'
  api:
    build: ./API
    container_name: API
    ports:
      - '5001:5000'
    volumes:
      - ./API
    environment:
      FLASK_ENV: development
